from collections.abc import Callable
from dataclasses import FrozenInstanceError
from hashlib import sha256
from random import Random

import pytest

from processing.errors import (
    ContentUnavailableError,
    UnsupportedConfigFormatError,
    UnsupportedSecretSyntaxError,
)
from processing.normalization import normalize_snapshot, normalize_text
from schemas import ConfigSnapshot


@pytest.mark.parametrize(
    ("content", "expected"),
    [
        ("", ""),
        (" \t\r\n\n", ""),
        ("logging enabled\r\ntimeout 30\rreplicas 2", "logging enabled\ntimeout 30\nreplicas 2\n"),
        ("\nlogging enabled \t\n\n\n timeout 30\n\n", "logging enabled\n\n timeout 30\n"),
        ("timeout\t 30\nreplicas  \t2", "timeout 30\nreplicas 2\n"),
        ("timeout \t=  30\nreplicas :  2", "timeout=30\nreplicas: 2\n"),
        ('description  "two  spaces"\n', 'description "two  spaces"\n'),
        ("  nested   value\n\tchild\tvalue", "  nested value\n\tchild value\n"),
        ("zeta 2\nalpha 1", "zeta 2\nalpha 1\n"),
        ("https://example.org/config", "https://example.org/config\n"),
        ("description Hà Nội\u2028site", "description Hà Nội\u2028site\n"),
        ("# generated at 10:00\nlogging enabled", "logging enabled\n"),
        ("  # GENERATED AT 2026-10-01T10:00:00Z\nlogging enabled", "logging enabled\n"),
        ("# last modified: yesterday\n! generated by demo\nlogging enabled", "logging enabled\n"),
        ("! generated\n", ""),
        ("first 1\n\n# generated at 10:00\n\nlast 2\n", "first 1\n\nlast 2\n"),
        ("# operator note\n! important\n", "# operator note\n! important\n"),
        ("# generated policy\n! generatedness\n", "# generated policy\n! generatedness\n"),
        ("logging enabled # generated at 10:00", "logging enabled # generated at 10:00\n"),
    ],
)
def test_normalize_text(content: str, expected: str) -> None:
    normalized = normalize_text(content)
    assert normalized == expected
    assert normalize_text(normalized) == normalized


@pytest.mark.parametrize("name", ["password", "passwd", "secret", "token", "api_key", "api-key"])
@pytest.mark.parametrize("separator", ["  ", " = ", ":", " :  "])
def test_secret_setting_masks_entire_value(name: str, separator: str) -> None:
    raw_value = '"synthetic-only value" # private annotation'
    normalized = normalize_text(f"  {name.upper()}{separator}{raw_value}\n")
    delimiter = "=" if "=" in separator else ": " if ":" in separator else " "
    expected = f"  {name.upper()}{delimiter}***\n"
    assert sha256(normalized.encode()).digest() == sha256(expected.encode()).digest()
    assert normalize_text(normalized) == normalized


@pytest.mark.parametrize("name", ["password_file", "tokenizer", "secretary", "description token"])
def test_unrecognized_setting_is_not_masked(name: str) -> None:
    assert normalize_text(f"{name} example") == f"{name} example\n"


@pytest.mark.parametrize("value", ["***", "", '""', "''", '"escaped \\" value"', "abc:def=ghi"])
def test_single_line_secret_syntax(value: str) -> None:
    normalized = normalize_text(f"password={value}")
    assert sha256(normalized.encode()).digest() == sha256(b"password=***\n").digest()


@pytest.mark.parametrize("syntax", ["continuation", "double", "single", "triple", "block"])
def test_multiline_secret_fails_closed(
    syntax: str, snapshot_factory: Callable[..., ConfigSnapshot], caplog: pytest.LogCaptureFixture
) -> None:
    synthetic_value = "synthetic-private-value"
    prefixes = {
        "continuation": f"{synthetic_value}\\",
        "double": f'"{synthetic_value}',
        "single": f"'{synthetic_value}",
        "triple": f'"""{synthetic_value}',
        "block": "|- # block value",
    }
    snapshot = snapshot_factory(f"password {prefixes[syntax]}\n{synthetic_value}")
    with pytest.raises(UnsupportedSecretSyntaxError, match="snap-001") as error:
        normalize_snapshot(snapshot)
    assert synthetic_value not in str(error.value)
    assert caplog.text == ""


def test_non_text_input_rejected_without_echo() -> None:
    with pytest.raises(TypeError, match="must be a string"):
        normalize_text(None)


def test_normalization_idempotent_for_seeded_line_combinations() -> None:
    random = Random(42)
    lines = [
        "",
        "  ",
        "timeout  30  ",
        "\tlogging\tenabled",
        "# generated at 10:00",
        "# ordinary note",
        "api-key = synthetic-value",
        "! generated by fixture",
        'description "keep  spaces"',
    ]
    for _ in range(100):
        content = "\r\n".join(random.choices(lines, k=20))
        normalized = normalize_text(content)
        assert normalize_text(normalized) == normalized


def test_normalized_snapshot_hash_and_identity(
    snapshot_factory: Callable[..., ConfigSnapshot],
) -> None:
    snapshot = snapshot_factory("description Hà Nội\n")
    original = snapshot.model_dump()
    normalized = normalize_snapshot(snapshot)
    assert (normalized.asset_id, normalized.snapshot_id, normalized.version) == (
        snapshot.asset_id,
        snapshot.snapshot_id,
        snapshot.version,
    )
    assert normalized.normalized_hash == sha256(normalized.normalized_content.encode()).hexdigest()
    assert normalize_snapshot(snapshot) == normalized
    assert snapshot.model_dump() == original
    with pytest.raises(FrozenInstanceError):
        normalized.normalized_hash = "not-a-hash"


@pytest.mark.parametrize("change", ["noise", "secret", "semantic"])
def test_raw_and_normalized_hash_semantics(
    change: str, snapshot_factory: Callable[..., ConfigSnapshot]
) -> None:
    old_content = "# generated at 10:00\nlogging enabled\npassword synthetic-before\n"
    new_content = {
        "noise": old_content.replace("10:00", "10:01").replace("logging ", "logging  "),
        "secret": old_content.replace("synthetic-before", "synthetic-after"),
        "semantic": old_content.replace("enabled", "disabled"),
    }[change]
    previous = snapshot_factory(old_content)
    current = snapshot_factory(new_content, snapshot_id="snap-002", version=2)
    assert previous.hash != current.hash
    old_normalized = normalize_snapshot(previous)
    new_normalized = normalize_snapshot(current)
    assert (old_normalized.normalized_hash == new_normalized.normalized_hash) == (
        change != "semantic"
    )
    assert (old_normalized.normalized_content == new_normalized.normalized_content) == (
        change != "semantic"
    )


@pytest.mark.parametrize("config_format", ["json", "yaml", "TEXT"])
def test_unsupported_format(
    snapshot_factory: Callable[..., ConfigSnapshot], config_format: str
) -> None:
    snapshot = snapshot_factory("synthetic-private-value", config_format=config_format)
    with pytest.raises(UnsupportedConfigFormatError, match="snap-001") as error:
        normalize_snapshot(snapshot)
    assert "synthetic-private-value" not in str(error.value)


def test_uri_only_content_is_not_fetched(snapshot_factory: Callable[..., ConfigSnapshot]) -> None:
    snapshot = snapshot_factory("", content_uri="s3://config-lake/private-object", content=None)
    with pytest.raises(ContentUnavailableError, match="router-001") as error:
        normalize_snapshot(snapshot)
    assert "private-object" not in str(error.value)


def test_normalized_repr_does_not_include_content(
    snapshot_factory: Callable[..., ConfigSnapshot],
) -> None:
    normalized = normalize_snapshot(snapshot_factory("unrecognized synthetic-private-value"))
    assert "synthetic-private-value" not in repr(normalized)
